-- ============================================================
-- Restaurant Martin - Esquema PostgreSQL (Supabase)
-- Ejecutar en: Supabase -> SQL Editor, o con `npm run db:init`
-- Es idempotente: se puede ejecutar varias veces sin perder datos.
-- ============================================================

-- Mantiene updated_at al día (equivalente a ON UPDATE CURRENT_TIMESTAMP de MySQL)
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS productos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    precio_kg NUMERIC(10,2) NOT NULL DEFAULT 0,
    precio_unidad NUMERIC(10,2) NOT NULL DEFAULT 0,
    precio_libra NUMERIC(10,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Relación padre -> hijo usando productos existentes (legado/compatibilidad)
-- Relacionado con:
-- - routes/productos.js (endpoints /api/productos/:padreId/hijos)
-- - public/js/mesas.js (fallback cuando no hay hijos-items)
CREATE TABLE IF NOT EXISTS producto_hijos (
    producto_padre_id INT NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
    producto_hijo_id INT NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (producto_padre_id, producto_hijo_id)
);

-- Hijos como "items" de texto (NO son productos, no tienen precio)
-- Ejemplo: Producto padre "CORRIENTE" -> items: "Goulash de cerdo", "Crema"
-- Relacionado con:
-- - routes/productos.js (endpoints /api/productos/:padreId/hijos-items)
-- - views/productos.ejs + public/js/productos.js (panel para administrar items)
-- - public/js/mesas.js (al montar pedido: seleccionar items y guardar en pedido_items.nota)
CREATE TABLE IF NOT EXISTS producto_hijos_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_padre_id INT NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
    nombre VARCHAR(120) NOT NULL,
    orden INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_padre_nombre UNIQUE (producto_padre_id, nombre)
);

CREATE TABLE IF NOT EXISTS clientes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    direccion TEXT,
    telefono VARCHAR(20),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS facturas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id INT REFERENCES clientes(id),
    fecha TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    total NUMERIC(10,2) NOT NULL,
    -- forma_pago se mantiene por compatibilidad (reportes/ventas); si hay varios pagos se guarda 'mixto'
    forma_pago VARCHAR(20) NOT NULL DEFAULT 'efectivo'
        CHECK (forma_pago IN ('efectivo','transferencia','tarjeta','qr','mixto'))
);

-- Pagos por factura (pago mixto: varias filas por la misma factura)
-- Relacionado con:
-- - routes/facturas.js (POST /api/facturas)
-- - routes/mesas.js (POST /api/mesas/pedidos/:id/facturar)
-- - views/factura.ejs (imprime el detalle de pagos)
CREATE TABLE IF NOT EXISTS factura_pagos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factura_id INT NOT NULL REFERENCES facturas(id) ON DELETE CASCADE,
    metodo VARCHAR(20) NOT NULL CHECK (metodo IN ('efectivo','transferencia','tarjeta','qr')),
    monto NUMERIC(10,2) NOT NULL,
    referencia VARCHAR(100) NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS detalle_factura (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factura_id INT REFERENCES facturas(id),
    producto_id INT REFERENCES productos(id),
    cantidad NUMERIC(10,2) NOT NULL,
    precio_unitario NUMERIC(10,2) NOT NULL,
    unidad_medida VARCHAR(5) DEFAULT 'KG' CHECK (unidad_medida IN ('KG','UND','LB')),
    subtotal NUMERIC(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS configuracion_impresion (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_negocio VARCHAR(100) NOT NULL,
    direccion TEXT,
    telefono VARCHAR(20),
    nit VARCHAR(50),
    pie_pagina TEXT,
    ancho_papel INT DEFAULT 80,
    font_size INT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    logo_data BYTEA,
    logo_tipo VARCHAR(50),
    qr_data BYTEA,
    qr_tipo VARCHAR(50),
    -- Modo cocina sin dispositivo: al enviar desde Mesas se imprime comanda y el item pasa a "listo".
    cocina_auto_listo_comanda SMALLINT NOT NULL DEFAULT 0,
    -- La comanda se imprime en el servidor (PC), no en el navegador del celular.
    cocina_imprime_servidor SMALLINT NOT NULL DEFAULT 0,
    impresora_comandas VARCHAR(150) NULL,
    impresora_facturas VARCHAR(150) NULL,
    factura_imprime_servidor SMALLINT NOT NULL DEFAULT 0,
    factura_copias INT NOT NULL DEFAULT 1,
    factura_auto_print SMALLINT NOT NULL DEFAULT 0
);

-- ===========================
-- USUARIOS / LOGIN / ROLES
-- Roles: administrador, mesero, cocinero
-- No se crea un admin por defecto: al abrir la app por primera vez, /setup pide crear el administrador.
-- Relacionado con: routes/auth.js, routes/usuarios.js, middleware/auth.js
-- ===========================
CREATE TABLE IF NOT EXISTS usuarios (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(100) NULL,
    password_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL DEFAULT 'mesero' CHECK (rol IN ('administrador','mesero','cocinero')),
    activo SMALLINT NOT NULL DEFAULT 1,
    last_login TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Tablas para restaurante: mesas, pedidos y items de pedido
CREATE TABLE IF NOT EXISTS mesas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(20) NOT NULL UNIQUE,
    descripcion VARCHAR(100),
    estado VARCHAR(20) DEFAULT 'libre' CHECK (estado IN ('libre','ocupada','reservada','bloqueada')),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pedidos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mesa_id INT NOT NULL REFERENCES mesas(id),
    cliente_id INT REFERENCES clientes(id),
    -- Nombre del usuario que abrió la comanda (snapshot para trazabilidad)
    mesero_nombre VARCHAR(100) NULL,
    estado VARCHAR(20) DEFAULT 'abierto'
        CHECK (estado IN ('abierto','en_cocina','preparando','listo','servido','cerrado','cancelado','rechazado')),
    total NUMERIC(10,2) NOT NULL DEFAULT 0,
    notas TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pedido_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id INT NOT NULL REFERENCES pedidos(id),
    producto_id INT NOT NULL REFERENCES productos(id),
    cantidad NUMERIC(10,2) NOT NULL,
    unidad_medida VARCHAR(5) DEFAULT 'UND' CHECK (unidad_medida IN ('KG','UND','LB')),
    precio_unitario NUMERIC(10,2) NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL,
    -- Estado del item (lo que cocina procesa). "rechazado" se usa para visualizar cancelaciones.
    estado VARCHAR(20) DEFAULT 'pendiente'
        CHECK (estado IN ('pendiente','enviado','preparando','listo','servido','cancelado','rechazado')),
    nota TEXT NULL,
    enviado_at TIMESTAMPTZ NULL,
    preparado_at TIMESTAMPTZ NULL,
    listo_at TIMESTAMPTZ NULL,
    servido_at TIMESTAMPTZ NULL,
    -- Cuándo la línea se incluyó en una comanda impresa (evita duplicar impresión)
    comanda_impresa_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- FUNCIONES MODERNAS (Restaurant Martin)
-- ============================================================

-- Carta digital: categoría, descripción y disponibilidad del producto
ALTER TABLE productos ADD COLUMN IF NOT EXISTS categoria VARCHAR(60);
ALTER TABLE productos ADD COLUMN IF NOT EXISTS descripcion TEXT;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS disponible SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS en_menu SMALLINT NOT NULL DEFAULT 1;

-- Foto del producto en tabla aparte (así SELECT * FROM productos no arrastra imágenes)
-- Relacionado con: routes/menu.js (GET /menu/img/:id) y routes/productos.js (subida)
CREATE TABLE IF NOT EXISTS producto_imagenes (
    producto_id INT PRIMARY KEY REFERENCES productos(id) ON DELETE CASCADE,
    data BYTEA NOT NULL,
    tipo VARCHAR(50) NOT NULL DEFAULT 'image/jpeg',
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Token del QR de cada mesa (el cliente abre /menu/<token>; no se puede adivinar)
ALTER TABLE mesas ADD COLUMN IF NOT EXISTS qr_token VARCHAR(40);
ALTER TABLE mesas ALTER COLUMN qr_token SET DEFAULT substr(md5(random()::text || clock_timestamp()::text), 1, 24);
UPDATE mesas SET qr_token = substr(md5(random()::text || clock_timestamp()::text || id::text), 1, 24) WHERE qr_token IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_mesas_qr_token ON mesas(qr_token);

-- Pagos en línea con Stripe (llaves propias del restaurante)
-- Relacionado con: services/stripe.js, routes/stripe.js, views/configuracion_stripe.ejs
ALTER TABLE configuracion_impresion ADD COLUMN IF NOT EXISTS stripe_habilitado SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE configuracion_impresion ADD COLUMN IF NOT EXISTS stripe_publishable_key VARCHAR(255);
ALTER TABLE configuracion_impresion ADD COLUMN IF NOT EXISTS stripe_secret_key_enc TEXT;
ALTER TABLE configuracion_impresion ADD COLUMN IF NOT EXISTS stripe_webhook_secret_enc TEXT;
ALTER TABLE configuracion_impresion ADD COLUMN IF NOT EXISTS moneda VARCHAR(3) NOT NULL DEFAULT 'usd';
ALTER TABLE configuracion_impresion ADD COLUMN IF NOT EXISTS app_url_publica VARCHAR(255);

-- Cada cobro con Stripe (Checkout Session). Se marca "usado" al quedar en una factura,
-- así un mismo pago no se puede aplicar dos veces.
CREATE TABLE IF NOT EXISTS stripe_pagos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(255) NOT NULL UNIQUE,
    pedido_id INT REFERENCES pedidos(id) ON DELETE SET NULL,
    monto NUMERIC(12,2) NOT NULL,
    moneda VARCHAR(3) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente'
        CHECK (estado IN ('pendiente','pagado','expirado','usado')),
    payment_intent VARCHAR(255),
    url TEXT,
    factura_id INT REFERENCES facturas(id) ON DELETE SET NULL,
    creado_por VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Avisos que el cliente envía desde el menú QR (llamar mesero, pedir cuenta, pedido nuevo)
CREATE TABLE IF NOT EXISTS mesa_alertas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mesa_id INT NOT NULL REFERENCES mesas(id) ON DELETE CASCADE,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('llamar_mesero','pedir_cuenta','nuevo_pedido')),
    mensaje TEXT,
    atendida SMALLINT NOT NULL DEFAULT 0,
    atendida_por VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    atendida_at TIMESTAMPTZ
);

-- Reservas (internas y desde la web pública /reservar)
CREATE TABLE IF NOT EXISTS reservas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    telefono VARCHAR(30),
    email VARCHAR(120),
    personas INT NOT NULL DEFAULT 2 CHECK (personas > 0),
    fecha_hora TIMESTAMPTZ NOT NULL,
    mesa_id INT REFERENCES mesas(id) ON DELETE SET NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente'
        CHECK (estado IN ('pendiente','confirmada','sentada','completada','cancelada','no_show')),
    origen VARCHAR(20) NOT NULL DEFAULT 'interno' CHECK (origen IN ('interno','web')),
    notas TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Inventario: insumos, recetas (insumos por producto) y movimientos
CREATE TABLE IF NOT EXISTS insumos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    unidad VARCHAR(20) NOT NULL DEFAULT 'und',
    stock NUMERIC(12,3) NOT NULL DEFAULT 0,
    stock_minimo NUMERIC(12,3) NOT NULL DEFAULT 0,
    costo_unitario NUMERIC(12,2) NOT NULL DEFAULT 0,
    activo SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recetas (
    producto_id INT NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
    insumo_id INT NOT NULL REFERENCES insumos(id) ON DELETE CASCADE,
    cantidad NUMERIC(12,3) NOT NULL CHECK (cantidad > 0),
    PRIMARY KEY (producto_id, insumo_id)
);

CREATE TABLE IF NOT EXISTS inventario_movimientos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    insumo_id INT NOT NULL REFERENCES insumos(id) ON DELETE CASCADE,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('entrada','salida','ajuste','venta')),
    cantidad NUMERIC(12,3) NOT NULL,
    stock_resultante NUMERIC(12,3),
    factura_id INT REFERENCES facturas(id) ON DELETE SET NULL,
    nota TEXT,
    usuario VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_mesa_alertas_pend ON mesa_alertas(atendida, created_at);
CREATE INDEX IF NOT EXISTS idx_reservas_fecha ON reservas(fecha_hora);
CREATE INDEX IF NOT EXISTS idx_inv_mov_insumo ON inventario_movimientos(insumo_id, created_at);
CREATE INDEX IF NOT EXISTS idx_stripe_pagos_pedido ON stripe_pagos(pedido_id);

CREATE INDEX IF NOT EXISTS idx_pedidos_mesa ON pedidos(mesa_id);
CREATE INDEX IF NOT EXISTS idx_pedido_items_pedido ON pedido_items(pedido_id);
CREATE INDEX IF NOT EXISTS idx_pedido_items_estado ON pedido_items(estado);
CREATE INDEX IF NOT EXISTS idx_facturas_fecha ON facturas(fecha);
CREATE INDEX IF NOT EXISTS idx_detalle_factura_factura ON detalle_factura(factura_id);
CREATE INDEX IF NOT EXISTS idx_factura_pagos_factura ON factura_pagos(factura_id);

-- Triggers updated_at
DO $$
DECLARE t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['productos','configuracion_impresion','usuarios','mesas','pedidos','pedido_items',
                             'stripe_pagos','reservas','insumos','producto_imagenes'] LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS trg_%s_updated_at ON %I', t, t);
        EXECUTE format('CREATE TRIGGER trg_%s_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()', t, t);
    END LOOP;
END $$;

-- ===========================
-- SEGURIDAD (Supabase)
-- Supabase expone las tablas del esquema public a través de su API REST con la "anon key".
-- Activamos RLS sin políticas: la API pública no puede leer ni escribir nada.
-- El servidor Node se conecta con el usuario postgres (DATABASE_URL), que no está sujeto a RLS.
-- ===========================
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE producto_hijos ENABLE ROW LEVEL SECURITY;
ALTER TABLE producto_hijos_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE facturas ENABLE ROW LEVEL SECURITY;
ALTER TABLE factura_pagos ENABLE ROW LEVEL SECURITY;
ALTER TABLE detalle_factura ENABLE ROW LEVEL SECURITY;
ALTER TABLE configuracion_impresion ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE mesas ENABLE ROW LEVEL SECURITY;
ALTER TABLE pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE pedido_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE producto_imagenes ENABLE ROW LEVEL SECURITY;
ALTER TABLE stripe_pagos ENABLE ROW LEVEL SECURITY;
ALTER TABLE mesa_alertas ENABLE ROW LEVEL SECURITY;
ALTER TABLE reservas ENABLE ROW LEVEL SECURITY;
ALTER TABLE insumos ENABLE ROW LEVEL SECURITY;
ALTER TABLE recetas ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventario_movimientos ENABLE ROW LEVEL SECURITY;
